-- =============================================================================
-- Stage 4 schema.
--
-- Everything lives in a dedicated schema so this lesson cannot collide with the
-- final project's tables in the same database.
-- =============================================================================

DROP SCHEMA IF EXISTS stage4 CASCADE;
CREATE SCHEMA stage4;
SET search_path TO stage4;

-- -----------------------------------------------------------------------------
-- Enums
--
-- A CHECK constraint or an enum? Both work. The enum is self-documenting and
-- shows up in the type system; the trade-off is that adding a value needs
-- ALTER TYPE (fine, and non-blocking since PG 12) and REMOVING one is genuinely
-- painful. Use an enum for a set that is stable - "status", "priority". Use a
-- lookup TABLE for anything users can edit.
-- -----------------------------------------------------------------------------
CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high');
CREATE TYPE task_status   AS ENUM ('todo', 'in_progress', 'done');

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
  -- Why UUID rather than SERIAL/IDENTITY?
  --   + ids can be generated by the client or another service, so you are not
  --     round-tripping to the database to learn what you just created
  --   + they leak nothing: /users/8134 tells a competitor how many users you
  --     have; a UUID does not (an "enumeration" leak)
  --   + they merge cleanly across shards and environments
  --   - 16 bytes instead of 4/8, and random insert order fragments the index
  -- For a training app the trade is clearly worth it. For a 10-billion-row
  -- append-only table, look at UUIDv7 or an identity column.
  --
  -- gen_random_uuid() is built in since PostgreSQL 13 - no pgcrypto needed.
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- CITEXT would be nicer but needs an extension. This is the portable way to
  -- get case-insensitive uniqueness: store as given, index the lowered value.
  -- See the unique index below.
  email        text        NOT NULL,
  display_name text        NOT NULL,

  -- TIMESTAMPTZ, ALWAYS. Never `timestamp` (without time zone).
  --
  -- `timestamptz` stores an absolute instant in UTC and converts on the way
  -- out. `timestamp` stores wall-clock digits with no context, so "2026-03-29
  -- 01:30" is ambiguous, unorderable across regions, and wrong twice a year.
  -- This is one of the few genuinely universal rules in schema design.
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  -- Constraints are documentation the database ENFORCES. A comment saying
  -- "email must contain @" is a wish; this is a guarantee.
  CONSTRAINT users_email_shape CHECK (email LIKE '%_@_%'),
  CONSTRAINT users_display_name_not_blank CHECK (length(trim(display_name)) > 0)
);

-- Case-insensitive uniqueness. A functional index on lower(email) means
-- 'Ada@example.com' and 'ada@example.com' cannot both exist.
CREATE UNIQUE INDEX users_email_lower_key ON users (lower(email));

-- -----------------------------------------------------------------------------
-- projects
-- -----------------------------------------------------------------------------
CREATE TABLE projects (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text        NOT NULL,

  -- FOREIGN KEY: the database refuses to store a project whose owner does not
  -- exist. Enforcing this in application code alone always fails eventually -
  -- a migration script, a manual fix, a race between two requests.
  --
  -- ON DELETE CASCADE: deleting a user deletes their projects.
  -- Choose this deliberately; the options are:
  --   RESTRICT / NO ACTION - refuse the delete (the safe default)
  --   CASCADE              - delete the children too (destructive, convenient)
  --   SET NULL             - orphan the children (needs a nullable column)
  owner_id   uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,

  created_at timestamptz NOT NULL DEFAULT now(),

  -- A project name is unique PER OWNER, not globally. A composite unique
  -- constraint expresses that exactly.
  CONSTRAINT projects_name_per_owner UNIQUE (owner_id, name),
  CONSTRAINT projects_name_not_blank CHECK (length(trim(name)) > 0)
);

-- -----------------------------------------------------------------------------
-- tasks
-- -----------------------------------------------------------------------------
CREATE TABLE tasks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  uuid          NOT NULL REFERENCES projects (id) ON DELETE CASCADE,

  -- Nullable + ON DELETE SET NULL: deleting a user must not delete the work.
  -- The task survives, unassigned. Compare with projects above - the right
  -- answer is different for each relationship, so decide it each time.
  assignee_id uuid          REFERENCES users (id) ON DELETE SET NULL,

  title       text          NOT NULL,
  description text,
  priority    task_priority NOT NULL DEFAULT 'medium',
  status      task_status   NOT NULL DEFAULT 'todo',

  -- DATE, not timestamptz: a due date is a calendar day, not an instant.
  -- Storing "due 2026-03-01" as a timestamp forces you to invent a time and a
  -- zone, and then it is due at a different moment for each user.
  due_date    date,

  -- NUMERIC for anything you do arithmetic on and care about.
  -- Never `float`/`double precision` for money or billable hours:
  --   SELECT 0.1::float8 + 0.2::float8  ->  0.30000000000000004
  -- NUMERIC(6,2) is exact: up to 9999.99.
  estimate_hours numeric(6, 2) CHECK (estimate_hours IS NULL OR estimate_hours > 0),

  created_at  timestamptz   NOT NULL DEFAULT now(),
  updated_at  timestamptz   NOT NULL DEFAULT now(),
  completed_at timestamptz,

  CONSTRAINT tasks_title_not_blank CHECK (length(trim(title)) > 0),

  -- A CROSS-COLUMN invariant. This is the kind of rule that quietly rots in
  -- application code, because every new code path has to remember it.
  -- The database remembers for you, forever, including for manual UPDATEs.
  CONSTRAINT tasks_completed_at_matches_status CHECK (
    (status = 'done'  AND completed_at IS NOT NULL) OR
    (status <> 'done' AND completed_at IS NULL)
  )
);

-- -----------------------------------------------------------------------------
-- tags, and a MANY-TO-MANY join table
-- -----------------------------------------------------------------------------
CREATE TABLE tags (
  id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE
);

CREATE TABLE task_tags (
  task_id uuid NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  tag_id  uuid NOT NULL REFERENCES tags  (id) ON DELETE CASCADE,

  -- A COMPOSITE PRIMARY KEY on both columns does two jobs at once: it
  -- identifies the row, and it makes tagging the same task twice impossible.
  -- No surrogate id is needed - the pair IS the identity.
  PRIMARY KEY (task_id, tag_id)
);

-- =============================================================================
-- INDEXES
--
-- An index is a trade: faster reads, slower writes, more disk. Add them for
-- queries you actually run, not speculatively.
--
-- The rules of thumb:
--   * index foreign keys you JOIN or filter on (PostgreSQL does NOT do this
--     for you - only PRIMARY KEY and UNIQUE get one automatically)
--   * index columns in WHERE and ORDER BY on hot paths
--   * in a composite index, COLUMN ORDER MATTERS: (a, b) serves
--     `WHERE a = ?` and `WHERE a = ? AND b = ?`, but NOT `WHERE b = ?`
--     (think of a phone book sorted by surname then first name)
-- =============================================================================

-- Foreign keys we join and filter on.
CREATE INDEX tasks_project_id_idx  ON tasks (project_id);
CREATE INDEX tasks_assignee_id_idx ON tasks (assignee_id);
CREATE INDEX projects_owner_id_idx ON projects (owner_id);

-- The hot query: "open tasks in this project, newest first".
-- The order (project_id, status, created_at DESC) matches how the query filters
-- and then sorts, so PostgreSQL can walk the index instead of sorting.
CREATE INDEX tasks_project_status_created_idx ON tasks (project_id, status, created_at DESC);

-- A PARTIAL index: only the rows that match the predicate are stored.
-- Most tasks eventually become 'done', so an index over just the open ones is
-- a fraction of the size and stays hot in cache.
CREATE INDEX tasks_open_due_idx ON tasks (due_date)
  WHERE status <> 'done' AND due_date IS NOT NULL;

-- Full-text search. `to_tsvector` normalises words (stemming, stop words) and
-- GIN is the index type for "many values per row".
-- A trailing `''` guards against NULL description making the whole vector NULL.
CREATE INDEX tasks_search_idx ON tasks
  USING gin (to_tsvector('english', title || ' ' || coalesce(description, '')));

-- =============================================================================
-- A TRIGGER to maintain updated_at
--
-- Doing this in application code means every code path must remember - and the
-- one that forgets is always the one you debug at 2am. Manual UPDATEs from a
-- SQL console never remember at all.
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tasks_set_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- A VIEW: a stored query, not a stored table.
--
-- Useful for keeping a definition of "the numbers everyone quotes" in one
-- place, so the dashboard and the report cannot disagree.
-- =============================================================================
CREATE VIEW project_summary AS
SELECT
  p.id            AS project_id,
  p.name          AS project_name,
  u.display_name  AS owner_name,
  count(t.id)                                        AS task_count,
  count(t.id) FILTER (WHERE t.status = 'done')       AS done_count,
  coalesce(sum(t.estimate_hours), 0)                 AS total_hours,
  coalesce(sum(t.estimate_hours) FILTER (WHERE t.status <> 'done'), 0) AS remaining_hours
FROM projects p
JOIN users u ON u.id = p.owner_id
-- LEFT JOIN so a project with no tasks still appears, with a count of 0.
-- An INNER JOIN here would silently drop empty projects from every report.
LEFT JOIN tasks t ON t.project_id = p.id
GROUP BY p.id, p.name, u.display_name;
